# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setBaseSize(QtCore.QSize(200, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView = QtWidgets.QListView(self.widget)
        self.listView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 779, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuchoose_color = QtWidgets.QMenu(self.menuBar)
        self.menuchoose_color.setObjectName("menuchoose_color")
        self.menuedit = MMenu(self.menuBar)
        self.menuedit.setObjectName("menuedit")
        MainWindow.setMenuBar(self.menuBar)
        self.actionRect = QtWidgets.QAction(MainWindow)
        self.actionRect.setCheckable(True)
        self.actionRect.setChecked(True)
        self.actionRect.setMenuRole(QtWidgets.QAction.PreferencesRole)
        self.actionRect.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionRect.setObjectName("actionRect")
        self.actionPolygon = QtWidgets.QAction(MainWindow)
        self.actionPolygon.setCheckable(True)
        self.actionPolygon.setObjectName("actionPolygon")
        self.actionbrush_color = QtWidgets.QAction(MainWindow)
        self.actionbrush_color.setObjectName("actionbrush_color")
        self.action_pen_color = QtWidgets.QAction(MainWindow)
        self.action_pen_color.setObjectName("action_pen_color")
        self.actionchange_pen = QtWidgets.QAction(MainWindow)
        self.actionchange_pen.setObjectName("actionchange_pen")
        self.actionchange_brush = QtWidgets.QAction(MainWindow)
        self.actionchange_brush.setObjectName("actionchange_brush")
        self.actionmove = QtWidgets.QAction(MainWindow)
        self.actionmove.setObjectName("actionmove")
        self.actionelipse = QtWidgets.QAction(MainWindow)
        self.actionelipse.setCheckable(True)
        self.actionelipse.setObjectName("actionelipse")
        self.actionround = QtWidgets.QAction(MainWindow)
        self.actionround.setCheckable(True)
        self.actionround.setObjectName("actionround")
        self.actionsegment = QtWidgets.QAction(MainWindow)
        self.actionsegment.setCheckable(True)
        self.actionsegment.setObjectName("actionsegment")
        self.actionray = QtWidgets.QAction(MainWindow)
        self.actionray.setCheckable(True)
        self.actionray.setObjectName("actionray")
        self.actionline = QtWidgets.QAction(MainWindow)
        self.actionline.setCheckable(True)
        self.actionline.setObjectName("actionline")
        self.actionpoly_line = QtWidgets.QAction(MainWindow)
        self.actionpoly_line.setCheckable(True)
        self.actionpoly_line.setObjectName("actionpoly_line")
        self.actionright_polygon = QtWidgets.QAction(MainWindow)
        self.actionright_polygon.setCheckable(True)
        self.actionright_polygon.setObjectName("actionright_polygon")
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRect)
        self.toolBar.addAction(self.actionPolygon)
        self.toolBar.addAction(self.actionright_polygon)
        self.toolBar.addAction(self.actionelipse)
        self.toolBar.addAction(self.actionround)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsegment)
        self.toolBar.addAction(self.actionray)
        self.toolBar.addAction(self.actionline)
        self.toolBar.addAction(self.actionpoly_line)
        self.menuchoose_color.addAction(self.actionbrush_color)
        self.menuchoose_color.addAction(self.action_pen_color)
        self.menuedit.addAction(self.actionchange_pen)
        self.menuedit.addAction(self.actionchange_brush)
        self.menuedit.addAction(self.actionmove)
        self.menuBar.addAction(self.menuchoose_color.menuAction())
        self.menuBar.addAction(self.menuedit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuchoose_color.setTitle(_translate("MainWindow", "choose color"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.actionRect.setText(_translate("MainWindow", "rect"))
        self.actionRect.setToolTip(_translate("MainWindow", "paint rect"))
        self.actionPolygon.setText(_translate("MainWindow", "polygon"))
        self.actionPolygon.setToolTip(_translate("MainWindow", "Polygon (double click to finish)"))
        self.actionbrush_color.setText(_translate("MainWindow", "brush color"))
        self.action_pen_color.setText(_translate("MainWindow", "pen color"))
        self.actionchange_pen.setText(_translate("MainWindow", "change pen"))
        self.actionchange_brush.setText(_translate("MainWindow", "change brush"))
        self.actionmove.setText(_translate("MainWindow", "move"))
        self.actionelipse.setText(_translate("MainWindow", "elipse"))
        self.actionround.setText(_translate("MainWindow", "round"))
        self.actionsegment.setText(_translate("MainWindow", "segment"))
        self.actionray.setText(_translate("MainWindow", "ray"))
        self.actionline.setText(_translate("MainWindow", "line"))
        self.actionpoly_line.setText(_translate("MainWindow", "poly line"))
        self.actionright_polygon.setText(_translate("MainWindow", "right polygon"))
from mmenu import MMenu
